/** Joint names */
export enum BoneJoint {
  root = "root",
  crest = "crest",
  waist = "waist",
  upperBody1 = "upperBody1",
  upperBody2 = "upperBody2",
  upperBody3 = "upperBody3",
  upperBody4 = "upperBody4",
  head = "head",
  rightEye = "rightEye",
  leftEye = "leftEye",
  rightEyebrow = "rightEyebrow",
  leftEyebrow = "leftEyebrow",
  rightArm = "rightArm",
  rightShoulder = "rightShoulder",
  rightElbow = "rightElbow",
  rightWrist = "rightWrist",
  rightFinger1 = "rightFinger1",
  rightFinger2 = "rightFinger2",
  rightFinger3 = "rightFinger3",
  rightFinger4 = "rightFinger4",
  rightFinger5 = "rightFinger5",
  leftArm = "leftArm",
  leftShoulder = "leftShoulder",
  leftElbow = "leftElbow",
  leftWrist = "leftWrist",
  leftFinger1 = "leftFinger1",
  leftFinger2 = "leftFinger2",
  leftFinger3 = "leftFinger3",
  leftFinger4 = "leftFinger4",
  leftFinger5 = "leftFinger5",
  rightHip = "rightHip",
  rightKnee = "rightKnee",
  rightAnkle = "rightAnkle",
  rightFoot = "rightFoot",
  leftHip = "leftHip",
  leftKnee = "leftKnee",
  leftAnkle = "leftAnkle",
  leftFoot = "leftFoot"
}

/** Dude model bone mapping */
export enum DudeJoints {
  root = 0,
  crest = 1,
  waist = 2,
  upperBody1 = 3,
  upperBody2 = 4,
  upperBody3 = 5,
  upperBody4 = 6,
  head = 7,
  rightEye = 10,
  leftEye = 11,
  rightEyebrow = 8,
  leftEyebrow = 9,
  rightArm = 12,
  rightShoulder = 13,
  rightElbow = 14,
  rightWrist = 15,
  rightFinger1 = 16,
  rightFinger2 = 19,
  rightFinger3 = 22,
  rightFinger4 = 25,
  rightFinger5 = 28,
  leftArm = 31,
  leftShoulder = 32,
  leftElbow = 33,
  leftWrist = 34,
  leftFinger1 = 35,
  leftFinger2 = 38,
  leftFinger3 = 41,
  leftFinger4 = 44,
  leftFinger5 = 47,
  rightHip = 50,
  rightKnee = 51,
  rightAnkle = 52,
  rightFoot = 53,
  leftHip = 54,
  leftKnee = 55,
  leftAnkle = 56,
  leftFoot = 57
}

/** Posenet joint names */
export enum PosenetBoneJoint {
  nose = "nose",
  leftEye = "leftEye",
  rightEye = "rightEye",
  leftEar = "leftEar",
  rightEar = "rightEar",
  leftShoulder = "leftShoulder",
  rightShoulder = "rightShoulder",
  leftElbow = "leftElbow",
  rightElbow = "rightElbow",
  leftWrist = "leftWrist",
  rightWrist = "rightWrist",
  leftHip = "leftHip",
  rightHip = "rightHip",
  leftKnee = "leftKnee",
  rightKnee = "rightKnee",
  leftAnkle = "leftAnkle",
  rightAnkle = "rightAnkle"
}

/** Posenet return values */
export enum PosenetJoints {
  nose = 0,
  leftEye = 1,
  rightEye = 2,
  leftEar = 3,
  rightEar = 4,
  leftShoulder = 5,
  rightShoulder = 6,
  leftElbow = 7,
  rightElbow = 8,
  leftWrist = 9,
  rightWrist = 10,
  leftHip = 11,
  rightHip = 12,
  leftKnee = 13,
  rightKnee = 14,
  leftAnkle = 15,
  rightAnkle = 16
}
